[build]
builder = "nixpacks"

[deploy]
startCommand = "PYTHONPATH=/app python backend/bot.py & PYTHONPATH=/app uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100